[package]
name = "koopa"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kp"
path = "./src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cliproc = "2.0"
colored = "2"
thiserror = "1.0"