name: Test
on:
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux-x64
          - os: windows-latest
            platform: windows-x64
          - os: macos-latest
            platform: macos-x64

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4
          
      - name: Configure Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Enable Cargo caching
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release --verbose

      - name: Test library
        run: cargo test --verbose
